### ISSUE TITLE
Demo ?

### ISSUE THREAD

**Issue by Naouak** [256MbTeam/Redmine-Scrumbler#1]
Hi,

Is it possible to get a zone where I can see the plugin working to know before I tried to install it if it is interesting for my team ?

Thanks,

**Comment by zloydadka** [comment]
coming soon

**Comment by zloydadka** [comment]
created demo 
http://demo.nishisha.net/

**Comment by xeta** [comment]
Maybe create default user, something like user/user with predefined roles and project. That can just create and move issues, and watch Scrumbler tabs.

**Comment by zloydadka** [comment]
all new users have priveleges.
i customized roles.

**Comment by xeta** [comment]
Это понятно. Просто регистрация напрягает. Зачем регистрироваться, чтобы просто посмотреть на плагин? Там же email нужно оставлять.

**Comment by pdesmarais** [comment]
The domain for the demo has not be renewed... Any plans?

**Comment by zloydadka** [comment]
i registred new domain. Demo coming soon

**Comment by raels** [comment]
Any updates yet?
