### ISSUE TITLE
URLs are absoulute

### ISSUE THREAD

**Issue by albert-mirzoyan** [256MbTeam/Redmine-Scrumbler#10]
My redmine is configured to work from 
www.example.com/redmine/

but scumbler generates thise like URL.
http://wwwin.example.com/projects/my_project/issues?tracker_id=1

Please use "Host name and path" setting to generate correct URLs.

Expected URL: http://wwwin.example.com/redmine/projects/my_project/issues?tracker_id=1

**Comment by xeta** [comment]
dup https://github.com/256MbTeam/Redmine-Scrumbler/issues/2
