### ISSUE TITLE
Routing error in Redmine trunk@8761

### ISSUE THREAD

**Issue by jwalkerbg** [256MbTeam/Redmine-Scrumbler#12]
Following is the log:

==== START LOG ====
Processing ProjectsController#settings (for 192.168.2.100 at 2012-02-04 08:19:26) [GET]
  Parameters: {"action"=>"settings", "id"=>"aproject", "controller"=>"projects", "tab"=>"modules"}
Rendering template within layouts/base
Rendering projects/settings

ActionView::TemplateError (No route matches {:project_id=>#<Project id: 1, name: "A project", description: "", homepage:
 "", is_public: true, parent_id: nil, created_on: "2011-12-25 22:05:42", updated_on: "2011-12-25 22:05:42", identifier:
"aproject", status: 1, lft: 1, rgt: 4>, :controller=>"scrumbler", :action=>"index"}) on line #56 of app/views/layouts/ba
se.html.erb:
53:
54:     <% if display_main_menu?(@project) %>
55:     <div id="main-menu">
56:         <%= render_main_menu(@project) %>
57:     </div>
58:     <% end %>
59: </div>

```
lib/redmine/menu_manager.rb:150:in `render_single_menu_node'
lib/redmine/menu_manager.rb:102:in `render_menu_node'
lib/redmine/menu_manager.rb:91:in `render_menu'
lib/redmine/menu_manager.rb:168:in `menu_items_for'
lib/redmine/menu_manager.rb:165:in `each'
lib/redmine/menu_manager.rb:165:in `menu_items_for'
lib/redmine/menu_manager.rb:90:in `render_menu'
lib/redmine/menu_manager.rb:80:in `render_main_menu'
app/views/layouts/base.html.erb:56
d:/Ruby187/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
d:/Ruby187/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
d:/Ruby187/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
d:/Ruby187/lib/ruby/1.8/webrick/server.rb:162:in `start'
d:/Ruby187/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
d:/Ruby187/lib/ruby/1.8/webrick/server.rb:95:in `start'
d:/Ruby187/lib/ruby/1.8/webrick/server.rb:92:in `each'
d:/Ruby187/lib/ruby/1.8/webrick/server.rb:92:in `start'
d:/Ruby187/lib/ruby/1.8/webrick/server.rb:23:in `start'
d:/Ruby187/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering D:/biz/apps/redmine_trunk/public/500.html (500 Internal Server Error)
==== END LOG ====

**Comment by zloydadka** [comment]
probably that's redmine error, not scrumbler's

**Comment by jwalkerbg** [comment]
Don't know, they changed many things in routing in Redmine.

**Comment by zloydadka** [comment]
no bug 
tested on 8864
