### ISSUE TITLE
ActionController::RoutingError in Scrumbler_sprints#settings 

### ISSUE THREAD

**Issue by albert-mirzoyan** [256MbTeam/Redmine-Scrumbler#18]
ActionController::RoutingError in Scrumbler_sprints#settings

Showing vendor/plugins/redmine_scrumbler/app/views/scrumbler_sprints/_issue_statuses.erb where line #1 raised:

update_issue_statuses_project_scrumbler_sprint_url failed to generate from {:project_id=>#<Project id: 19, name: "PuuPaa", description: "", homepage: "", is_public: true, parent_id: nil, created_on: "2012-02-08 17:54:14", updated_on: "2012-02-08 18:03:14", identifier: "puupaa", status: 1, lft: 1, rgt: 2, if_config_pf: true, model_id: 1>, :controller=>"scrumbler_sprints", :action=>"update_issue_statuses", :id=>nil}, expected: {:controller=>"scrumbler_sprints", :action=>"update_issue_statuses"}, diff: {:project_id=>#<Project id: 19, name: "PuuPaa", description: "", homepage: "", is_public: true, parent_id: nil, created_on: "2012-02-08 17:54:14", updated_on: "2012-02-08 18:03:14", identifier: "puupaa", status: 1, lft: 1, rgt: 2, if_config_pf: true, model_id: 1>, :id=>nil}

Extracted source (around line #1):

1: <% form_tag update_issue_statuses_project_scrumbler_sprint_url(@project, @project_sprint) do%>
2:   <table class="list">
3:     <thead>
4:       <tr>

Trace of template inclusion: app/views/common/_tabs.rhtml, vendor/plugins/redmine_scrumbler/app/views/scrumbler_sprints/settings.erb

RAILS_ROOT: x:/xampp/redmine
Application Trace | Framework Trace | Full Trace

x:/xampp/redmine/vendor/rails/actionpack/lib/action_controller/routing/route_set.rb:426:in `raise_named_route_error'
x:/xampp/redmine/vendor/rails/actionpack/lib/action_controller/routing/route_set.rb:387:in`generate'
x:/xampp/redmine/vendor/rails/actionpack/lib/action_controller/url_rewriter.rb:205:in `rewrite_path'
x:/xampp/redmine/vendor/rails/actionpack/lib/action_controller/url_rewriter.rb:184:in`rewrite_url'
x:/xampp/redmine/vendor/rails/actionpack/lib/action_controller/url_rewriter.rb:162:in `rewrite'
x:/xampp/redmine/vendor/rails/actionpack/lib/action_controller/base.rb:634:in`url_for'
x:/xampp/redmine/vendor/rails/actionpack/lib/action_view/helpers/url_helper.rb:85:in `send'
x:/xampp/redmine/vendor/rails/actionpack/lib/action_view/helpers/url_helper.rb:85:in`url_for'
(eval):16:in `update_issue_statuses_project_scrumbler_sprint_url'
x:/xampp/redmine/app/views/common/_tabs.rhtml:24:in`_run_rhtml_app47views47common47_tabs46rhtml_locals_object_tabs'
x:/xampp/redmine/app/views/common/_tabs.rhtml:23:in `each'
x:/xampp/redmine/app/views/common/_tabs.rhtml:23:in`_run_rhtml_app47views47common47_tabs46rhtml_locals_object_tabs'
x:/xampp/redmine/app/helpers/application_helper.rb:204:in `render_tabs'

Request

Parameters:

{"project_id"=>"puupaa",
 "method"=>:get,
 "id"=>"2"}

Show session dump
Response

Headers:

{"Content-Type"=>"",
 "Cache-Control"=>"no-cache"}

**Comment by zloydadka** [comment]
fixed

**Comment by vsushkov** [comment]
Experiencing the same issue. Scrumbler version is 42b29d782cd2604e0dbe4baa4c7832f035009ff5

**Comment by xeta** [comment]
Fixed in c1b2a712acc4aed88782b0dce7567bc96aa97937
