### ISSUE TITLE
Блокируются настройки полей в проекте

### ISSUE THREAD

**Issue by Kreozot** [256MbTeam/Redmine-Scrumbler#19]
В проекте в активным модулем Scrumbler невозможно изменить набор настраиваемых полей.
Версия Scrumbler - 1.3.0
Версия Redmine - 1.2.1.stable (MySQL)

P.S. Ничего, что по-русски?

**Comment by zloydadka** [comment]
ничего что по-русски.
но другие жители гитхаба не поймут к сожалению.

**Comment by Kreozot** [comment]
Ну главное чтобы создатели поняли.
Данная проблема только у меня?

**Comment by zloydadka** [comment]
мы ее обнаружили и починили.
в новой версии появится исправление. завтпа скорей всего выложим.
