### ISSUE TITLE
routing error

### ISSUE THREAD

**Issue by zloydadka** [256MbTeam/Redmine-Scrumbler#2]
When you click the #420 link in the box, it routes us to a 404 error at http://host.com/issues/420.  For our bitnami instance at least, it needs to direct us to http://host.com/redmine/ issues/420

**Comment by ycdesu** [comment]
I've a similar issue. Icons of this plugins are not loaded. I try to find out the image urls using chrome console and it shows something like this: http://<my-ip>/images/2uparrow.png. I think it should be http://<my-ip>/redmine/images/2uparrow.png.

The same issue occurred while using dragAndDrop in backlog utility. I drag an feature from the backlog to the sprint, the chrome console prints a 404 not found ( http://<my-ip>/projects/testProject/scrumbler_backlogs/change_issue_version). It should be http://<my-ip>/redmine/projects/testProject/scrumbler_backlogs/change_issue_version.

My redmine folder: /usr/share/redmine, and link the /usr/share/redmine/public to /var/www/redmine.

This is my setting in sites-enable/default. Thanks for helping.

<VirtualHost *:80>

```
     DocumentRoot /var/www
    <Directory />
            Options FollowSymLinks
            AllowOverride None
    </Directory>
    <Directory /var/www/>
            Options FollowSymLinks MultiViews
            AllowOverride None
            Order allow,deny
            allow from all
    </Directory>

    ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
    <Directory "/usr/lib/cgi-bin">
            AllowOverride None
            Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
            Order allow,deny
            Allow from all
    </Directory>

    RailsBaseURI /redmine
    <Directory /var/www/redmine>
       RailsEnv production
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log

    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel warn

    CustomLog ${APACHE_LOG_DIR}/access.log combined

Alias /doc/ "/usr/share/doc/"
<Directory "/usr/share/doc/">
    Options Indexes MultiViews FollowSymLinks
    AllowOverride None
    Order deny,allow
    Deny from all
    Allow from 127.0.0.0/255.0.0.0 ::1/128
</Directory>
```

</VirtualHost>
