### ISSUE TITLE
NoMethodError (undefined method `value' for nil:NilClass)

### ISSUE THREAD

**Issue by cforce** [256MbTeam/Redmine-Scrumbler#20]
Calling url https://redmine.srv/projects/spielwiese/scrumbler_sprints/11/burndown

raises error

Processing ScrumblerSprintsController#burndown (for 172.16.104.6 at 2012-02-09 17:56:25) [GET]
I, [2012-02-09T17:56:25.071131 #29168]  INFO -- :   Parameters: {"project_id"=>"spielwiese", "action"=>"burndown", "id"=>"11", "controller"=>"scrumbler_sprints"}
D, [2012-02-09T17:56:25.072231 #29168] DEBUG -- :   [4;35;1mSQL (0.4ms)[0m   [0mSELECT max(`settings`.updated_on) AS max_updated_on FROM `settings` [0m
D, [2012-02-09T17:56:25.073259 #29168] DEBUG -- :   [4;36;1mUser Load (0.3ms)[0m   [0;1mSELECT \* FROM `users` WHERE (`users`.`id` = 3) AND (users.status = 1) AND ( (`users`.`type` = 'User' OR `users`.`type` = 'AnonymousUser' ) ) [0m
D, [2012-02-09T17:56:25.074233 #29168] DEBUG -- :   [4;35;1mProject Load (0.3ms)[0m   [0mSELECT \* FROM `projects` WHERE (`projects`.`identifier` = 'spielwiese') LIMIT 1[0m
D, [2012-02-09T17:56:25.074739 #29168] DEBUG -- :   [4;36;1mScrumblerProjectSetting Load (0.2ms)[0m   [0;1mSELECT \* FROM `scrumbler_project_settings` WHERE (`scrumbler_project_settings`.project_id = 105) LIMIT 1[0m
D, [2012-02-09T17:56:25.075548 #29168] DEBUG -- :   [4;35;1mScrumblerSprint Load (0.2ms)[0m   [0mSELECT scrumbler_sprints.*, name FROM `scrumbler_sprints` INNER JOIN `versions` ON `versions`.id = `scrumbler_sprints`.version_id WHERE (`scrumbler_sprints`.`id` = 11 AND (`scrumbler_sprints`.project_id = 105)) [0m
D, [2012-02-09T17:56:25.076339 #29168] DEBUG -- :   [4;36;1mVersion Load (0.2ms)[0m   [0;1mSELECT \* FROM `versions` WHERE (`versions`.`id` = 116) [0m
D, [2012-02-09T17:56:25.076927 #29168] DEBUG -- :   [4;35;1mProject Load (0.2ms)[0m   [0mSELECT \* FROM `projects` WHERE (`projects`.`id` = 105) [0m
D, [2012-02-09T17:56:25.077236 #29168] DEBUG -- :   [4;36;1mCACHE (0.0ms)[0m   [0;1mSELECT \* FROM `scrumbler_project_settings` WHERE (`scrumbler_project_settings`.project_id = 105) LIMIT 1[0m
D, [2012-02-09T17:56:25.079117 #29168] DEBUG -- :   [4;35;1mIssue Load (0.4ms)[0m   [0mSELECT \* FROM `issues` WHERE (`issues`.`status_id` IN ('11','12','13','14','9','15','1','10','4','5') AND `issues`.`tracker_id` IN ('1','2','4') AND `issues`.`fixed_version_id` = 116) [0m
D, [2012-02-09T17:56:25.080350 #29168] DEBUG -- :   [4;36;1mUser Load (0.3ms)[0m   [0;1mSELECT \* FROM `users` WHERE (`users`.`id` IN (185,3)) AND ( (`users`.`type` = 'User' OR `users`.`type` = 'AnonymousUser' ) ) [0m
D, [2012-02-09T17:56:25.081162 #29168] DEBUG -- :   [4;35;1mIssueStatus Load (0.2ms)[0m   [0mSELECT \* FROM `issue_statuses` WHERE (`issue_statuses`.`id` IN (1,5)) [0m
D, [2012-02-09T17:56:25.081960 #29168] DEBUG -- :   [4;36;1mIssuePriority Load (0.2ms)[0m   [0;1mSELECT \* FROM `enumerations` WHERE (`enumerations`.`id` = 4) AND ( (`enumerations`.`type` = 'IssuePriority' ) ) [0m
D, [2012-02-09T17:56:25.083799 #29168] DEBUG -- :   [4;35;1mCustomValue Load Including Associations (0.5ms)[0m   [0mSELECT `custom_values`.`id` AS t0_r0, `custom_values`.`customized_type` AS t0_r1, `custom_values`.`customized_id` AS t0_r2, `custom_values`.`custom_field_id` AS t0_r3, `custom_values`.`value` AS t0_r4, `custom_fields`.`id` AS t1_r0, `custom_fields`.`type` AS t1_r1, `custom_fields`.`name` AS t1_r2, `custom_fields`.`field_format` AS t1_r3, `custom_fields`.`possible_values` AS t1_r4, `custom_fields`.`regexp` AS t1_r5, `custom_fields`.`min_length` AS t1_r6, `custom_fields`.`max_length` AS t1_r7, `custom_fields`.`is_required` AS t1_r8, `custom_fields`.`is_for_all` AS t1_r9, `custom_fields`.`is_filter` AS t1_r10, `custom_fields`.`position` AS t1_r11, `custom_fields`.`searchable` AS t1_r12, `custom_fields`.`default_value` AS t1_r13, `custom_fields`.`editable` AS t1_r14, `custom_fields`.`visible` AS t1_r15 FROM `custom_values` LEFT OUTER JOIN `custom_fields` ON `custom_fields`.id = `custom_values`.custom_field_id WHERE (`custom_values`.customized_id = 872 AND `custom_values`.customized_type = 'Issue') ORDER BY custom_fields.position[0m
F, [2012-02-09T17:56:25.086306 #29168] FATAL -- : 
NoMethodError (undefined method `value' for nil:NilClass):
  vendor/plugins/redmine_scrumbler/app/controllers/scrumbler_sprints_controller.rb:122:in`burndown'
  vendor/plugins/redmine_scrumbler/app/controllers/scrumbler_sprints_controller.rb:121:in `each'
  vendor/plugins/redmine_scrumbler/app/controllers/scrumbler_sprints_controller.rb:121:in`inject'
  vendor/plugins/redmine_scrumbler/app/controllers/scrumbler_sprints_controller.rb:121:in `burndown'
  vendor/plugins/redmine_scrumbler/app/controllers/scrumbler_sprints_controller.rb:120:in`map'
  vendor/plugins/redmine_scrumbler/app/controllers/scrumbler_sprints_controller.rb:120:in `burndown'
  passenger (3.0.8) lib/phusion_passenger/rack/request_handler.rb:96:in`process_request'
  passenger (3.0.8) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
  passenger (3.0.8) lib/phusion_passenger/abstract_request_handler.rb:274:in`main_loop'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in`send'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
  passenger (3.0.8) lib/phusion_passenger/utils.rb:479:in`safe_fork'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in`**send**'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:180:in `start'
  passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in`start'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
  passenger (3.0.8) lib/phusion_passenger/abstract_server_collection.rb:132:in`lookup_or_add'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
  passenger (3.0.8) lib/phusion_passenger/abstract_server_collection.rb:82:in`synchronize'
  passenger (3.0.8) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:213:in`spawn_rails_application'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
  passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:275:in`handle_spawn_application'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.8) helper-scripts/passenger-spawn-server:99

I, [2012-02-09T17:56:25.088116 #29168]  INFO -- : Rendering /opt/redmine-1.2.1d3/public/500.html (500 Internal Server Error)

**Comment by cforce** [comment]
The error seems to disappear if at least one issue in the versions burndown has an scrum point set to sth other than default value "?"

**Comment by zloydadka** [comment]
we know this error, it's fixed in the nearest release.
error raises if you dont set points manually on issues created before plugin install

**Comment by zloydadka** [comment]
fixed in 1.3.2
