### ISSUE TITLE
private method `gsub' called for {}:HashWithIndifferentAccess

### ISSUE THREAD

**Issue by jorgebg** [256MbTeam/Redmine-Scrumbler#21]
Hi!

I just installed the plugin on a fresh installation of Redmine 1.3.1. When I try to activate the module on the Settings tab I get the following error:

```
private method `gsub' called for {}:HashWithIndifferentAccess
```

Here is the application trace:
http://pastebin.com/zXUpEQj3

**Request**

Parameters:

``` javascript
{"commit"=>"Save",
 "authenticity_token"=>"XtL7PwatqQf6dghy6QX+d8Uc2grJ8q45dqZr6pQ=",
 "id"=>"test",
 "enabled_module_names"=>["issue_tracking",
 "time_tracking",
 "news",
 "documents",
 "files",
 "wiki",
 "repository",
 "boards",
 "calendar",
 "gantt",
 "redmine_scrumbler"]}
```

**Response**

Headers:

``` javascript
{"Content-Type"=>"",
 "Cache-Control"=>"no-cache"}
```

Thanks!

**Comment by zloydadka** [comment]
no bug 
tested on 8864

**Comment by jorgebg** [comment]
Hello zloydadka

I updated to version 1.4.0 and I am still getting the same error.

**Comment by zloydadka** [comment]
i dont know how repeat your error.

what database and other plugins do you use?

**Comment by jorgebg** [comment]
It is a fresh install.
The database is sqlite.

I just pushed it to a repository:
https://github.com/jorgebg/heroku-redmine-scrumbler

Ignore the "heroku" prefix of the project, I am testing it on local.

**Comment by zloydadka** [comment]
can you privide login and password to instance?

**Comment by jorgebg** [comment]
Sure:

admin / admin
 El 14/02/2012 11:04, "Alexander Andrianov" <
reply@reply.github.com>
escribi:

**Comment by zloydadka** [comment]
doesnt work

**Comment by be-st** [comment]
Hi, I have same issue.

Request:

{"enabled_module_names"=>["issue_tracking",
 "documents",
 "wiki",
 "repository",
 "redmine_scrumbler"],
 "id"=>"bagioni",
 "authenticity_token"=>"VtcN61xxYsmG4N2TKmEUUtHSBZuF39R+mZW1l9/DNVw=",
 "commit"=>"Save"}

Redmine 1.3.1 installed on windows with SQLite.

**Comment by xeta** [comment]
Ok guys, we found this bug. Will be fixed in few days.

**Comment by zloydadka** [comment]
it's active record sqlite internal error
https://gist.github.com/rails/rails/issues/581

to fix it, we create hack for this in plugin
pull last commit from master and test it.

**Comment by be-st** [comment]
It works. Thanks a lot.

**Comment by jorgebg** [comment]
It works! Thank you very much :)
