### ISSUE TITLE
Setting a max sprint point value for every / a sprint

### ISSUE THREAD

**Issue by danielplappert** [256MbTeam/Redmine-Scrumbler#25]
It would be nice to set a max sprint point value for every sprint. And if you want to add a task / ticket with a sprint point, which will exceed the max. value of the current sprint, the ticket will be rejected and not be added to the sprint.

**Comment by zloydadka** [comment]
done
try lastest version from master 1.4.3

**Comment by danielplappert** [comment]
Thanks. Works great!!!
