### ISSUE TITLE
Postgres SUM(text) error

### ISSUE THREAD

**Issue by AugustusCosta** [256MbTeam/Redmine-Scrumbler#26]
Processing ScrumblerSprintsController#burndown (for 187.114.123.52 at 2012-02-13 08:42:41) [GET]
  Parameters: {"id"=>"1", "controller"=>"scrumbler_sprints", "action"=>"burndown", "project_id"=>"cochilo-android"}

ActiveRecord::StatementInvalid (PGError: ERROR:  function sum(text) does not exist
LINE 1: select sum(value) from custom_values where 
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
: select sum(value) from custom_values where 
custom_values.custom_field_id = 1 and
custom_values.customized_type = 'Issue' and
custom_values.customized_id in (2,8,6,5,4,3,0) and
custom_values.value <> '?'):
  vendor/plugins/redmine_scrumbler/app/models/scrumbler_sprint.rb:58:in `points_total'
  vendor/plugins/redmine_scrumbler/app/controllers/scrumbler_sprints_controller.rb:127:in`burndown'
  /home/desenvolvimento/.rvm/rubies/ruby-1.8.7-p357/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /home/desenvolvimento/.rvm/rubies/ruby-1.8.7-p357/lib/ruby/1.8/webrick/httpserver.rb:65:in`run'
  /home/desenvolvimento/.rvm/rubies/ruby-1.8.7-p357/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /home/desenvolvimento/.rvm/rubies/ruby-1.8.7-p357/lib/ruby/1.8/webrick/server.rb:162:in`start'
  /home/desenvolvimento/.rvm/rubies/ruby-1.8.7-p357/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /home/desenvolvimento/.rvm/rubies/ruby-1.8.7-p357/lib/ruby/1.8/webrick/server.rb:95:in`start'
  /home/desenvolvimento/.rvm/rubies/ruby-1.8.7-p357/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /home/desenvolvimento/.rvm/rubies/ruby-1.8.7-p357/lib/ruby/1.8/webrick/server.rb:92:in`start'
  /home/desenvolvimento/.rvm/rubies/ruby-1.8.7-p357/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /home/desenvolvimento/.rvm/rubies/ruby-1.8.7-p357/lib/ruby/1.8/webrick/server.rb:82:in`start'

**Comment by zloydadka** [comment]
try to check lastest version of plugin 
this error fixed a hour ago
