### ISSUE TITLE
Wrong URL used

### ISSUE THREAD

**Issue by snicke** [256MbTeam/Redmine-Scrumbler#27]
Our redmine installation is located at servername.domainexample.com/redmine/
The webserver listens to port 8080.

When i click "Settings" in Scrumbler the correct URL is generated but when I click "Backlog" the following URL is generated and the page is not found:

localhost:8080/redmine/....

It seems like the "Host name and path" is not used when clicking the "Backlog" link but used correctly when cklicking other links, for example "Setttings" and "All sprints"

When the webserver is listening to 0.0.0.0:80 it works but we need to configure redmine using port 8080.

**Comment by xeta** [comment]
I change url generation for this link. Try v1.4.1.
