### ISSUE TITLE
Generating Sprints statistics hangs and CPU 100%

### ISSUE THREAD

**Issue by be-st** [256MbTeam/Redmine-Scrumbler#28]
Hi, when I try to get Statistics for a sprint (for example projects/test/scrumbler_sprints/1/burndown) Redmine hangs and CPU goes to 100%.

Redmine 1.3.1 - Scrumbler 1.4 SQLite and Windows (with Mingle)

**Comment by zloydadka** [comment]
how many tasks in your sprint?

**Comment by be-st** [comment]
Only 1... I'm testing Scrumbler

**Comment by zloydadka** [comment]
it,s strange.
we used scrumbler with sprints with 20-30 issues. and it working perfectly on statistics.
unfortunately dont have windows instances of redmine and cant test it.

what version of ruby and browser do you use?

**Comment by be-st** [comment]
I'm using Chrome 16.0.912.77 and Ruby 1.8.7.

Now I've tried also with Firefox.
I get a script busy message on:

http://localhost:3000/plugin_assets/redmine_scrumbler/javascripts/highstock/highstock.js?1329219754:232

**Comment by be-st** [comment]
Seems it hangs on this row:

function(a,c){if(a.visible!==!1&&(b=b.concat(a.processedXData),c)){b.sort(function(a,b){return a-b});for(c=b.length-1;c--;)b[c]===b[c+1]&&b.splice(c,1)}});a=b.length;if(a>2){d=b[1]-b[0];for(e=a-1;e--&&!c;)b[e+1]-b[e]!==d&&(c=!0)}c?

**Comment by zloydadka** [comment]
try lastest version from master

**Comment by zloydadka** [comment]
fixed in 1.4.2

**Comment by be-st** [comment]
It works. Thank you very much
