### ISSUE TITLE
when i install the plugin , rake db error

### ISSUE THREAD

**Issue by archonwang** [256MbTeam/Redmine-Scrumbler#29]
rake db:migrate_plugins RAILS_ENV=production

shows error

uninitialized constant ActiveRecord::ConnectionAdapters::SQLite3Adapter

I'm not sure why it happened?

my enviroment:
redmine 1.3.1
rails 2.3.14
mysql 5.5.X

windows xp sp3

anyone has any idea? thanks

**Comment by zloydadka** [comment]
we fix it today

**Comment by zloydadka** [comment]
fixed. pull last version from master
