### ISSUE TITLE
rake db:migrate_plugins errors

### ISSUE THREAD

**Issue by archonwang** [256MbTeam/Redmine-Scrumbler#30]
interesting error.

I ran [rake db:migrate_plugins] and found error.

==  CreateScrumblerProjectSettings: migrating =================================
-- create_table(:scrumbler_project_settings)
   -> 0.3750s
==  CreateScrumblerProjectSettings: migrated (0.3750s) ========================

==  UpdateScrumblerMaintrackers: migrating ====================================
-- drop_table(:scrumbler_maintrackers)
rake aborted!
An error has occurred, all later migrations canceled:

Mysql::Error: Unknown table 'scrumbler_maintrackers': DROP TABLE `scrumbler_maintrackers`

(See full trace by running task with --trace)

I checked it, and found in folder /migrate/, the rb file loaded not by orders.

so I modified the rb files into 101_XXX.rb, 102_XXX.rb... and rake again. It's OK.

I used windows xp sp3,redmine 1.3.1, mysql 5.5.X. 

Anyone has the same error like me ??

**Comment by zloydadka** [comment]
fixed in last commit in master
