### ISSUE TITLE
Support for chiliproject?

### ISSUE THREAD

**Issue by derEremit** [256MbTeam/Redmine-Scrumbler#31]
Just migrated to chiliproject 3.0 due to lack of support in redmine.

could this be ported??

**Comment by zloydadka** [comment]
It isn't in our business domain.
If you want you can fork our project.

**Comment by derEremit** [comment]
does that mean you would never do that, or could you be paid to support chiliproject?

**Comment by zloydadka** [comment]
i'm today try to install plugin on chiliproject
 it works
but need small fixes

version with chiliproject support will be released on next week

**Comment by derEremit** [comment]
wow, great, thanks for your effort

**Comment by zloydadka** [comment]
try lastest version from master 1.4.3
