### ISSUE TITLE
Wrong URL used (again - now other links)

### ISSUE THREAD

**Issue by snicke** [256MbTeam/Redmine-Scrumbler#33]
Our redmine installation is located at servername.domainexample.com/redmine/
The webserver listens to port 8080.

When i click "Settings" and now also "Backlog" (thanks for fixing that bug) in Scrumbler the correct URL is generated but when I click "Statistics" and "Sprint Settings" (and also when klicking on the sprint links and "Edit" links under "settings" and on the tracker link and issue number on any issue on the dashboard aswell as all the links in the backlog (tracker type, issue number) etc...) the following URL is generated and the page is not found:

localhost:8080/redmine/....

It seems like the "Host name and path" is not used when clicking the "Backlog" link but used correctly when cklicking other links, for example "Setttings" and "All sprints"

When the webserver is listening to 0.0.0.0:80 it works but we need to configure redmine using port 8080.

Note: There are probably more links than those stated above generating the "page not found"-error. Please check all the links in Scrumbler.

**Comment by zloydadka** [comment]
try lastest version from master 1.4.3

**Comment by zloydadka** [comment]
can you post bit of your server configuration file with redmine dir

**Comment by snicke** [comment]
I'm not sure what you mean/want from me. Please elaborate a bit.

**Comment by zloydadka** [comment]
apache or nginx selection with redmine configuration
