### ISSUE TITLE
template error

### ISSUE THREAD

**Issue by govereem** [256MbTeam/Redmine-Scrumbler#35]
ActionView::TemplateError (No plugin called 'redmine_scrumbler' - please use the full name of a loaded plugin.) on line #20 of app/views/layouts/base.html.erb:
17:       body {behavior: url(<%= stylesheet_path "csshover.htc" %>);}
18:     </style>
19: <![endif]-->
20: <%= call_hook :view_layouts_base_html_head %>
21: 
22: <%= yield :header_tags -%>
23: </head>

```
lib/redmine/hook.rb:63:in `send'
```

**Comment by zloydadka** [comment]
please read installation instructions in README.md
