### ISSUE TITLE
Невозможно конкретизировать задачи в спринте

### ISSUE THREAD

**Issue by Kreozot** [256MbTeam/Redmine-Scrumbler#36]
Добрый день.
Хочется иметь возможность конкретизировать задачи в спринте уже после планирования. Ограничение на добавление задач в распланированном спринте понятно, но на мой взгляд, можно было бы оставить его только на верхнем уровне иерархии. У нас, например, верхним уровнем служит user story, а ниже уже идёт конкретизация по задачам, которая соответственно может меняться во время спринта (логически в спринте при этом ничего не меняется - user story остаются теми же).
Можно ли сделать так, чтобы ограничение работало только на задачи верхнего уровня? Либо сделать это опцией, доступной через настройки.

**Comment by xeta** [comment]
Добрый день.
Ну вы например можете оценивать только задачи верхнего уровня, а все остальные оставлять с пустыми поинтами.

**Comment by xeta** [comment]
В версии 1.5 сделаем, чтобы можно было добавлять подзадачи в открытый спринт.

**Comment by Kreozot** [comment]
Поинтами, если честно, мы не пользуемся - используем оценку по времени, что уже реализовано редмайном. Речь идёт больше о том, чтобы подзадача была в той же версии (в том же спринте).
С нетерпением жду версии 1.5. Спасибо.

**Comment by xeta** [comment]
Выложили новую версию. Теперь оценки подзадач не влияют на итоговую.
