### ISSUE TITLE
Disabled trackers show up in backlog

### ISSUE THREAD

**Issue by lociii** [256MbTeam/Redmine-Scrumbler#37]
Steps to reproduce:
- Create a fresh tracker
- Create new issue on that tracker
- Disable usage of the tracker in scrumbler settings (not sprint settings)

Expected result:
- Tracker is hidden in backlog, not only greyed out

Current result:
- Tracker shows up in backlog (greyed out)

Is this behaviour intended?
Why would I like to see an issue of a disabled tracker that I cannot assign to any sprint?

Thanks for a great plugin anyway!

**Comment by xeta** [comment]
You can enable Tracker only for one Sprint. General settings assigned to all sprints by default, but you can create specific settings to each sprint.

**Comment by xeta** [comment]
In version 1.5 disabled issues are hided.
