### ISSUE TITLE
Nothing shown in backlog

### ISSUE THREAD

**Issue by snicke** [256MbTeam/Redmine-Scrumbler#38]
Nothing is shown when I click the backlog link in scrumbler version 1.4.3

**Comment by snicke** [comment]
Same as issue #40 I would say.

**Comment by zloydadka** [comment]
can you open chrome console or ff firebug
and enter into it "Scrumbler" and write output here

**Comment by Hawkin** [comment]
I have the same problem. The javascript console in Chrome shows this error:

Uncaught TypeError: Object http://localhost/redmine/projects/demons/scrumbler_backlogs# has no method 'on'
buildIssueCreationFormLinkscrumbler-backlog.js:92
Class.create.createUIscrumbler-backlog.js:700
Class.create.initializescrumbler-backlog.js:616
klassprototype.js:89
(anonymous function)scrumbler_backlogs:103

**Comment by zloydadka** [comment]
will be fixed today

**Comment by zloydadka** [comment]
fixed
try lastest version from ee17d82a2d6ce9756d82fb7475214b15cb725f3f@master

**Comment by Hawkin** [comment]
Thanks a lot for quick response. Great job!

**Comment by snicke** [comment]
Working. Thanks and great job!
