### ISSUE TITLE
No plugin called 'redmine_scrumbler' 

### ISSUE THREAD

**Issue by yquenechdu** [256MbTeam/Redmine-Scrumbler#4]
Hi

When I use Redmine 1.3.0, with your plugin, I obtain this error message : 
RuntimeError in Scrumbler#index
Showing vendor/plugins/Redmine-Scrumbler/app/views/scrumbler/index.html.erb where line #2 raised:
No plugin called 'redmine_scrumbler' - please use the full name of a loaded plugin.

When I installed your plugin, the directory name is Redmine-Scrumbler, but the system call redmine_scrumbler

I renamed the directory in redmine_scrumbler, it's good.

Fix your code :) 

Cheers
Yannick

**Comment by zloydadka** [comment]
about it written in the readme in in installation block
