### ISSUE TITLE
rake db:migrate:plugin NAME=redmine_scrumbler Issue

### ISSUE THREAD

**Issue by RobinOBrien** [256MbTeam/Redmine-Scrumbler#44]
Hi, 

Trying to get the plugin to work. Im running Redmine 1.3.1 on Ubuntu 10.10

But when i try to run rake "db:migrate:plugin NAME=redmine_scrumbler" the following message appears:

"rake aborted!
Unknown database 'redmine_development'"

I tried to create the table in the database and it then moves on but gets to a point where a table is missing.

Im not sure how to get past this error.

Any help will be greatly appreciated.

**Comment by zloydadka** [comment]
may de you use other envinorment, not development?

if you use production add RAILS_ENV=production
