### ISSUE TITLE
Backlog's drag and drop is semi-working

### ISSUE THREAD

**Issue by nMustaki** [256MbTeam/Redmine-Scrumbler#52]
Hello,

first, thanks for your plugin :-)

Second, I have an issue when trying to drag and drop a feature/task between the backlog and the sprint columns. It says "Something went wrong" , but if I reload the page, the feature/task has been switched ok.

Also, I can't add an issue which is at the end of backlog column, because I can't go up to where I activate the "Something went wrong" dialog.

It is reproductible on Chromium and Firefox, both on latest stable version.

Thanks you !
Nathan

**Comment by snicke** [comment]
+1 Can confirm the bug in 1.50.

**Comment by xeta** [comment]
We cant reproduce this bug. Can you post error logs from server and browser console?

**Comment by chagel** [comment]
+1 

## i have the same error on lastest version.

Processing ScrumblerBacklogsController#change_issue_version (for xx at 2012-03-17 21:18:24) [POST]
  Parameters: {"sprint_id"=>"1", "project_id"=>"crius", "issue_id"=>"308", "action"=>"change_issue_version", "controller"=>"scrumbler_backlogs"}
Sending email notification to: ....

NoMethodError (undefined method `link_to' for #<ScrumblerBacklogsController:0xb6de707c>):
  vendor/plugins/redmine_scrumbler/app/helpers/scrumbler_helper.rb:50:in`prepare_issue_subject'
  vendor/plugins/redmine_scrumbler/app/helpers/scrumbler_helper.rb:49:in `prepare_issue_subject'
  vendor/plugins/redmine_scrumbler/app/helpers/scrumbler_backlogs_helper.rb:23:in`prepare_issues_for_json'
  vendor/plugins/redmine_scrumbler/app/helpers/scrumbler_backlogs_helper.rb:20:in `map'
  vendor/plugins/redmine_scrumbler/app/helpers/scrumbler_backlogs_helper.rb:20:in`prepare_issues_for_json'
  vendor/plugins/redmine_scrumbler/app/helpers/scrumbler_backlogs_helper.rb:71:in `prepare_backlog_for_json'
  vendor/plugins/redmine_scrumbler/app/controllers/scrumbler_backlogs_controller.rb:81:in`change_issue_version'

**Comment by xeta** [comment]
Ok, i solve this bug. This error appears only for issues with subtasks. Try master branch.

**Comment by Tiennd** [comment]
I have the same issue now. The message "Some thing wrong" displays when the button "Move to TOP" is clicked then nothing done.

Thanks,
Tien
