### ISSUE TITLE
Error 500 after Installation

### ISSUE THREAD

**Issue by stf675** [256MbTeam/Redmine-Scrumbler#53]
Bitnami Redmine 1.3

Ran rake db:migrate_plugins NAME=redmine_scrumbler RAILS_ENV=production  (it says migrate_plugin in instruction but it gives "Don't know how to build task 'db:migrate_plugin'", so I assume it iwas a typo)

Processing WelcomeController#index (for 10.8.4.51 at 2012-03-06 10:35:17) [GET]
  Parameters: {"action"=>"index", "controller"=>"welcome"}
Rendering template within layouts/base
Rendering welcome/index

ActionView::TemplateError (No plugin called 'redmine_scrumbler' - please use the full name of a loaded plugin.) on line #20 of app/views/layouts/base.html.erb:
17:       body {behavior: url(<%= stylesheet_path "csshover.htc" %>);}
18:     </style>
19: <![endif]-->
20: <%= call_hook :view_layouts_base_html_head %>
21: 
22: <%= yield :header_tags -%>
23: </head>

```
lib/redmine/hook.rb:63:in `send'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:60:in `tap'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:144:in `call_hook'
app/views/layouts/base.html.erb:20
config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in `dispatch_cgi'
```

Rendering C:/Program Files/BitNami Redmine Stack131/apps/redmine/public/500.html (500 Internal Server Error)

Also the results from migrate_plugins command:

C:\Program Files\BitNami Redmine Stack131\apps\redmine>rake db:migrate_plugins NAME=redmine_scrumbler RAILS_ENV=production
(in C:/Program Files/BitNami Redmine Stack131/apps/redmine)
Migrating engines...
Migrating Redmine_Scrumbler...
==  CreateScrumblerSprints: migrating =========================================
-- create_table(:scrumbler_sprints, {:force=>true})
   -> 0.1250s
==  CreateScrumblerSprints: migrated (0.1250s) ================================

==  CreateScrumblerProjectSettings: migrating =================================
-- create_table(:scrumbler_project_settings, {:force=>true})
   -> 0.0781s
==  CreateScrumblerProjectSettings: migrated (0.0781s) ========================

==  RemoveDeprecatedMigrations: migrating =====================================
==  RemoveDeprecatedMigrations: migrated (0.0156s) ============================

==  UpdateScrumblerSprints: migrating =========================================
-- add_column(:scrumbler_sprints, :max_points, :integer, {:null=>false, :default
=>0})
   -> 0.2187s
==  UpdateScrumblerSprints: migrated (0.2187s) ================================

==  AddFactCloseDateFieldScrumblerSprints: migrating ==========================
-- add_column(:scrumbler_sprints, :fact_close_date, :date)
   -> 0.0937s
==  AddFactCloseDateFieldScrumblerSprints: migrated (0.1094s) =================

Migrating acts_as_activity_provider...
Migrating acts_as_attachable...
Migrating acts_as_customizable...
Migrating acts_as_event...
Migrating acts_as_list...
Migrating acts_as_searchable...
Migrating acts_as_tree...
Migrating acts_as_versioned...
Migrating acts_as_watchable...
Migrating awesome_nested_set...
Migrating classic_pagination...
Migrating gravatar...
Migrating issue_hot_buttons_plugin...
Migrating myneid-Redmine-Periodic-Task-53146c5...
Migrating open_id_authentication...
Migrating prepend_engine_views...
Migrating redmine_better_gantt_chart...
Migrating redmine_issue_checklist...
Migrating redmine_knowledgebase...
Migrating rfpdf...
Migrating ruby-net-ldap-0.0.4...
Migrating wadewomersley-redmine-auto-percent-b523688...

**Comment by stf675** [comment]
Also I looked in closed issue https://github.com/256MbTeam/Redmine-Scrumbler/issues/35 that describe the same problem, and suggestion to read Readme.MD file.  But I believe that file contain number of errors:

you have to specify RAILS_ENV=production and the command is rake db:migrate_plugins

**Comment by zloydadka** [comment]
just rename plugin dir to redmine_scrumbler in vendor/plugins

**Comment by stf675** [comment]
that the name I used

**Comment by stf675** [comment]
Looks like someone closed that issue, but it not resolved my plugin folder name was always "redmine_scrumbler".

As soon as I restart services - I got 500 error, than I removed plugin folder, restart services again and redmine worked.   Copying folder back without further restart has no effect.

Anything else I can try to fix it?

-----Original Message-----

**Comment by stf675** [comment]
fixed by moving plugin folder out, restarting redmine, copying folder back and restarting again
