### ISSUE TITLE
Error when disabling and re-enabling plugin

### ISSUE THREAD

**Issue by potiuk** [256MbTeam/Redmine-Scrumbler#58]
First of all - great plugin.

I am using latest version of scrumbler from git (e0e14bafed11869ff0a34c1fb97a334f42ef293c). Redmine 1.3.2 stable (2e1467de92378d2cd4b723e2f0557119bcee4f10) from git.

I enabled scrumbler for a project, updated some version (set start/end date and such, moved tasks around and generally played with it a bit).

Then I disabled the plugin (disabled the module) ... All fine so far.
Now when I tried to re-enable it, I got (when I press save in project's setttings with enabled scrumbler) I got internal error 500

Processing ProjectsController#modules (for 213.17.174.238 at 2012-04-09 23:14:33) [POST]
  Parameters: {"commit"=>"Save", "action"=>"modules", "id"=>"desert-tycoon", "authenticity_token"=>"1VOdQRKYh1I+/M9e3ug1BR1qneraSNMVM6cOz/xNTcM=", "controller"=>"projects", "enabled_module_names"=>["issue_tracking", "documents", "repository", "gantt", "redmine_scrumbler"]}

NoMethodError (undefined method `effective_date' for nil:NilClass):
  vendor/plugins/redmine_scrumbler/app/models/scrumbler_sprint.rb:100:in`end_date'
  vendor/plugins/redmine_scrumbler/app/models/scrumbler_sprint.rb:134:in `start_end_date_validation'
  app/models/project.rb:543:in`enabled_module_names='
  app/controllers/projects_controller.rb:213:in `modules'
  /usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:95:in`process_request'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:374:in`start_request_handler'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:332:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/utils.rb:184:in`safe_fork'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:330:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in`**send**'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in`start_synchronously'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:163:in `start'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:209:in`start'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:126:in`lookup_or_add'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:80:in`synchronize'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:255:in`spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:287:in`handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in`main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  /usr/lib/phusion_passenger/passenger-spawn-server:61

Rendering /usr/share/redmine-git/public/500.html (500 Internal Server Error)

**Comment by HotfixGuru** [comment]
I tried using Version.effective_date (Attribute of Class Version) and Version.due_date (Method to access Version.effective_date), which are both definded in version.rb inside Redmine-Models.

But this does not do much.
It produces almost the same error as above: 
NoMethodError (undefined method `effective_date' for #<Class:0x7f31752203c8>): (obvious since this is an attribute)
...
or
NoMethodError (undefined method`due_date' for #Class:0x7fc42bbb9378): (dont know why this doesnt work)
...

Any ideas?

**Comment by malsmith** [comment]
I've got this same problem with the same scenario.

**Comment by HotfixGuru** [comment]
Is there a way to fix this via reinstallation of scrumbler? How can I deinstall scrumbler?

**Comment by xeta** [comment]
fixed with 5abe3e0015580baa7e2f8395dcdc18f42ae91ca8
