### ISSUE TITLE
Custom Issue Statuses and Trackers always unchecked by default

### ISSUE THREAD

**Issue by hawkhead99** [256MbTeam/Redmine-Scrumbler#59]
First off, great app!  This will really simplify sprints for me.

When I create a new sprint utilizing Scrumbler > backlog > plus symbol next to the sprint drop down, all of my custom issue statuses and custom trackers are left off by default.  There should be a Scrumbler setting to set your default statuses and trackers for each new sprint.

Also, when I add my custom trackers/sprints, positions for existing items do not auto-roll down based on the number I choose.

I could live without the auto-roll down fix if it would just default all my custom items and use the same standard positions that are already set in the admin settings.

**Comment by xeta** [comment]
If you check your custom trackers and issue statuses at "Scrumbler settings", they will be active for all new sprints by default.

**Comment by hawkhead99** [comment]
Thanks for the reply Ivan.

I may have missed that part initially...  I noticed when I reloaded
scrumbler, it auto picked up all the custom fields that I added since
loading it the first time lol.

I will watch this area if I have any more custom things added.  Thanks again

On Wed, Apr 25, 2012 at 8:10 AM, Ivan Kotenko <
reply@reply.github.com

> wrote:
> 
> If you check your custom trackers and issue statuses at "Scrumbler
> settings", they will be active for all new sprints by default.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/256MbTeam/Redmine-Scrumbler/issues/59#issuecomment-5330715

## 

Scott Brazelton
276-451-4765
1936 Bradley Drive
Montgomery, IL 60538
