### ISSUE TITLE
Documentation of the way Scrumbler works

### ISSUE THREAD

**Issue by slanglade** [256MbTeam/Redmine-Scrumbler#65]
Hi,

Is there some kind of documentation describing the way scrumbler works and plug into Redmine? I know I could dig into the code by myself the "real men don't click" way, but being a pure RoR beginner it could help...

**Comment by xeta** [comment]
You can find installation instruction here: 
https://github.com/256MbTeam/Redmine-Scrumbler/blob/master/README.md
And some usage instructions here:
https://github.com/256MbTeam/Redmine-Scrumbler/wiki/Documentation-and-overview

**Comment by slanglade** [comment]
Well, I was looking for something more like a technical doc. But thanks anyway, and this plugin is really usefull to our team... So they are beginning to ask for customization, and my RoR skills suck badly. Maybe I need to dwelve into it.

Again, thanks for your help.
