### ISSUE TITLE
Security : Scrumbler accessible from anonymous user

### ISSUE THREAD

**Issue by letic** [256MbTeam/Redmine-Scrumbler#66]
Hey there,

While testing I found out that any user can access to Scrumbler if they know the URL despite the permissions set.

This is reproducible on the demo. 

For example : http://demo.nishisha.net/projects/testdrive doesn't show the Scrumbler tab to anonymous user but you can access http://demo.nishisha.net/projects/testdrive/scrumbler

This wouldn't be too big an issue if all sprints and issues weren't visible.

I don't have the time to have a look right now but I'll try to investigate the issue.

Cheers
LeTic

**Comment by crazydan** [comment]
I can confirm this issue with Redmine Redmine 1.3.0.stable.8442 and Scrumbler 1.5.0.

**Comment by xeta** [comment]
fixed with 1d0f520dca6855b7d22a5c0d8e4b8a60c7788c75
