### ISSUE TITLE
Add order in backlog

### ISSUE THREAD

**Issue by farf** [256MbTeam/Redmine-Scrumbler#73]
Hello, 

Thanks for this great tool. It would be much better if you could add the order in the backlog. Instead of managing priority, just drag and drop to change the order of tasks.

Have you already thought on that?

**Comment by wonko** [comment]
+1

**Comment by AlexMikhalev** [comment]
+1 for order or "priority score" from 0 100(0), so it can be sorted on priority score.

**Comment by zloydadka** [comment]
duplicated #32
